version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@aws-cdk/*'
      - dependency-name: 'aws-cdk'
      - dependency-name: 'aws-sdk'
    open-pull-requests-limit: 10
