version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
    cooldown:
      default-days: 15
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@aws-cdk/*'
      - dependency-name: 'aws-cdk'
      - dependency-name: 'aws-sdk'
    open-pull-requests-limit: 10
    cooldown:
      default-days: 15
