version = 1


[merge]
method = "squash"
automerge_label = "automerge 🚀"

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_coauthors = true
include_pull_request_url = true