version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
method = "squash"
automerge_label = "automerge 🚀"

[merge.message]
title = "pull_request_title"
include_coauthors = true
include_pull_request_url = true